// Generated by crates/conduit-api/tests/frontend_contract.rs. Do not edit by hand.

import type { EventEnvelope } from "./events";
import type { OperatorStatusSnapshot, ProviderStatus } from "./status";

export type DateTimeString = string;
export type IdString = string;
export type NodeKind =
  | "source"
  | "wake_word"
  | "stt"
  | "speaker_id"
  | "core"
  | "transform"
  | "tts"
  | "sink";

export type MemoryMode = "read" | "write" | "read_write";
export type MemoryScope = "conversation" | "speaker" | "global";
export type Modality = "audio" | "text" | "utterance";

export interface PipelineNodeBase {
  id: IdString;
  provider: string;
}

/// Provider-specific settings, whose names and value types come from the
/// settings schema the provider's descriptor declares rather than from this
/// contract — which is the point: adding a setting to a provider must not mean
/// regenerating the frontend's types.
export type ProviderSettings = Record<string, unknown>;

export type ConfirmPolicy = "never" | "always";

/// `settings` is what this pipeline overrides on the Configured Provider it
/// names, and nothing more: everything the provider was configured with still
/// applies to settings the binding leaves out.
export interface ModelBinding {
  provider: string;
  model?: string;
  settings?: ProviderSettings;
}

export interface ToolBinding {
  provider: string;
  confirm: ConfirmPolicy;
}

export interface MemoryBinding {
  provider: string;
  mode: MemoryMode;
  scope?: MemoryScope;
  limit: number;
}

export interface ReasoningCore {
  model: ModelBinding;
  system?: string;
  tools?: ToolBinding[];
  memory?: MemoryBinding[];
  max_rounds: number;
}

export type PipelineNode =
  | (PipelineNodeBase & { kind: "source"; modality?: Modality })
  | (PipelineNodeBase & { kind: "wake_word" })
  | (PipelineNodeBase & { kind: "stt"; settings?: ProviderSettings })
  | (PipelineNodeBase & { kind: "speaker_id" })
  | (PipelineNodeBase & { kind: "transform" })
  | (PipelineNodeBase & { kind: "tts"; voice?: string; settings?: ProviderSettings })
  | (PipelineNodeBase & { kind: "sink"; modality?: Modality })
  | { kind: "core"; id: IdString; core: ReasoningCore };

export interface PipelineEdge {
  from: IdString;
  to: IdString;
  port?: string;
}

export interface PipelineGraph {
  name: string;
  nodes: PipelineNode[];
  edges: PipelineEdge[];
}

export interface PipelineView {
  graph: PipelineGraph;
  order: IdString[];
}

export type AudioEncoding = "pcm_s16_le" | "pcm_f32_le" | "opus" | "flac";

export interface AudioFormat {
  encoding: AudioEncoding;
  sample_rate: number;
  channels: number;
}

export interface PipelineTestRequest {
  utterance?: string;
  format?: AudioFormat;
}

export interface PipelineTestResult {
  pipeline: string;
  conversation: IdString;
  status: "completed";
  audio_bytes: number;
  reply_text?: string;
  reply_audio?: string;
}

export type ComponentConfigValueType =
  | "string"
  | "boolean"
  | "integer"
  | "string_list";
export type ComponentConfigFormat = "url";

export interface ComponentConfigProperty {
  type: ComponentConfigValueType;
  format?: ComponentConfigFormat;
  pattern?: string;
  /// The only values this field accepts, when it is a closed set — a wake
  /// word engine, for instance. Absent means the field is open.
  options?: string[];
}

export interface ComponentConfigSchema {
  properties: Record<string, ComponentConfigProperty>;
  required: string[];
}

export interface ProviderComponentDescriptor {
  id: string;
  label: string;
  kind: ProviderCapability;
  definition_variant: ProviderDefinitionVariantType;
  schema: ComponentConfigSchema;
}

export interface ProviderComponentCatalog {
  components: ProviderComponentDescriptor[];
}

export type ProviderCapability =
  | "stt"
  | "llm"
  | "tts"
  | "transform"
  | "tool"
  | "wake"
  | "speaker_id";
/// Inner provider definition variant, paired with `kind` (the outer variant)
/// to name the full two-level provider definition variant.
export type ProviderDefinitionVariantType =
  | "openai"
  | "wyoming"
  | "mcp"
  | "builtin"
  | "openwakeword"
  | "nanowakeword"
  | "microwakeword"
  | "http"
  | "diarization_server";

/// The three wake word detectors Conduit speaks to. Each is its own wake
/// variant, because the three do not run in the same places.
export type WakeEngine = "microwakeword" | "openwakeword" | "nanowakeword";

/// The embedding models a speaker identification service may be running.
export type SpeakerEngine = "speechbrain" | "resemblyzer" | "pyannote";

export type ProviderSecret =
  | { type: "inline"; value: string }
  | { type: "external"; reference: string }
  | { type: "redacted" };

export type LlmVariant = {
  type: "openai";
  base_url: string;
  api_key?: ProviderSecret;
  models: string[];
  streaming: boolean;
  system_prompt?: string;
};

export type SttVariant =
  | {
      type: "openai";
      base_url: string;
      model: string;
      api_key?: ProviderSecret;
      stream: boolean;
    }
  | {
      type: "wyoming";
      url: string;
      model?: string;
      streaming: boolean;
    };

export type TtsVariant =
  | {
      type: "openai";
      base_url: string;
      model: string;
      api_key?: ProviderSecret;
      voices: string[];
    }
  | {
      type: "wyoming";
      url: string;
      voice?: string;
      streaming: boolean;
    };

export type ToolVariant = {
  type: "mcp";
  transport: McpTransport;
};

/// One rewriting rule that ships with Conduit. Named rather than configurable
/// because each is a statement about how speech differs from writing.
export type TransformRule =
  | "strip_emoji"
  | "markdown_to_speech"
  | "collapse_whitespace";

export type TransformVariant = {
  type: "builtin";
  rules: TransformRule[];
};

/// Where a detector Conduit can score itself is running.
export type WakeRuntime =
  | {
      where: "local";
      models_dir?: string;
      threshold_percent: number;
    }
  | {
      where: "wyoming";
      url: string;
      threshold_percent: number;
    };

/// Where microWakeWord is running. A different set from `WakeRuntime`, not a
/// subset: its models cannot be scored in process, and it is the only engine
/// small enough for satellite hardware.
export type MicroWakeWordRuntime =
  | { where: "device" }
  | {
      where: "wyoming";
      url: string;
      threshold_percent: number;
    };

export type WakeVariant =
  | {
      type: "openwakeword";
      runtime: WakeRuntime;
      phrases: string[];
    }
  | {
      type: "nanowakeword";
      runtime: WakeRuntime;
      phrases: string[];
    }
  | {
      type: "microwakeword";
      runtime: MicroWakeWordRuntime;
      phrases: string[];
    };

export type SpeakerIdVariant =
  | {
      type: "diarization_server";
      base_url: string;
      threshold_percent: number;
    }
  | {
      type: "http";
      base_url: string;
      api_key?: ProviderSecret;
      engine: SpeakerEngine;
      threshold_percent: number;
    };

export type ProviderDefinitionVariant =
  | { type: "llm"; variant: LlmVariant }
  | { type: "stt"; variant: SttVariant }
  | { type: "tts"; variant: TtsVariant }
  | { type: "transform"; variant: TransformVariant }
  | { type: "tool"; variant: ToolVariant }
  | { type: "wake"; variant: WakeVariant }
  | { type: "speaker_id"; variant: SpeakerIdVariant };

export type McpTransport =
  | { type: "sse"; url: string }
  | { type: "streamable_http"; url: string }
  | { type: "stdio"; command: string; args: string[] };

export interface ProviderDefinition {
  id: string;
  label: string;
  variant: ProviderDefinitionVariant;
}

/// One voice a synthesizer can speak with.
export interface Voice {
  id: string;
  name: string;
  language: string;
}

/// The voices a synthesizer offers.
///
/// An empty list is a real answer: a provider that accepts any voice name has
/// no catalogue, and the editor lets an operator type one instead.
export interface ProviderVoices {
  provider: string;
  voices: Voice[];
}

/// The phrases a wake word detector offers.
///
/// An empty list is a real answer, for the same reason: a Wyoming server
/// scores whatever it loaded and enumerates nothing, and a satellite knows
/// only what it was flashed with.
export interface ProviderPhrases {
  provider: string;
  phrases: string[];
}

export interface ProviderDefinitionView {
  id: string;
  label: string;
  kind: ProviderCapability;
  variant: ProviderDefinitionVariant;
  settings?: ProviderSettings;
}

export type TurnStatus = "running" | "completed" | "cancelled" | "failed" | "degraded";
export type UtteranceSegmentRole = "assistant_preamble" | "tool_output" | "assistant_response";
export type ToolCallStatus =
  | "requested"
  | "running"
  | "completed"
  | "failed"
  | "denied"
  | "awaiting_confirmation";

export interface TurnList {
  turns: TurnSummary[];
}

export interface TurnSummary {
  turn_id: IdString;
  conversation_id: IdString;
  pipeline_name: string;
  status: TurnStatus;
  started_at: DateTimeString;
  ended_at?: DateTimeString;
  sequence: number;
}

export interface TurnSnapshot {
  turn_id: IdString;
  conversation_id: IdString;
  pipeline_name: string;
  status: TurnStatus;
  cancellation_reason?: string;
  started_at: DateTimeString;
  ended_at?: DateTimeString;
  sequence: number;
  items: ReconstructionItem[];
}

export type ReconstructionItem = UtteranceSegmentItem | ToolBatchItem;

export interface UtteranceSegmentItem {
  kind: "utterance_segment";
  id: string;
  sequence: number;
  role: UtteranceSegmentRole;
  modality: Modality;
  text: string;
  started_at: DateTimeString;
  evidence: IdString[];
}

export interface ToolBatchItem {
  kind: "tool_batch";
  id: string;
  sequence: number;
  model_round: number;
  calls: ToolCall[];
  started_at: DateTimeString;
  completed_at?: DateTimeString;
  evidence: IdString[];
}

export interface ToolCall {
  id: IdString;
  name?: string;
  status: ToolCallStatus;
  duration_ms?: number;
  error?: string;
  evidence: IdString[];
}

export interface RawTurnEvents {
  turn_id: IdString;
  events: EventEnvelope[];
}

export interface TurnReconstructionUpdate {
  turn_id: IdString;
  conversation_id: IdString;
  pipeline_name: string;
  sequence: number;
  update: "snapshot_changed";
}

export interface ConduitApiClientConfig {
  baseUrl: string;
  headers?: () => HeadersInit;
  fetch?: typeof fetch;
}

export interface ConduitApiClient {
  readonly routes: typeof conduitApiRoutes;
  status: () => Promise<OperatorStatusSnapshot>;
  listPipelines: () => Promise<string[]>;
  listProviderComponents: () => Promise<ProviderComponentCatalog>;
  listProviderDefinitions: () => Promise<string[]>;
  getProviderDefinition: (id: string) => Promise<ProviderDefinitionView>;
  putProviderDefinition: (
    id: string,
    definition: ProviderDefinition,
  ) => Promise<ProviderDefinitionView>;
  deleteProviderDefinition: (id: string) => Promise<void>;
  testProviderDefinition: (id: string) => Promise<ProviderStatus>;
  listProviderVoices: (id: string) => Promise<ProviderVoices>;
  listProviderPhrases: (id: string) => Promise<ProviderPhrases>;
  getPipeline: (name: string) => Promise<PipelineView>;
  putPipeline: (name: string, graph: PipelineGraph) => Promise<PipelineView>;
  deletePipeline: (name: string) => Promise<void>;
  validatePipeline: (graph: PipelineGraph) => Promise<PipelineView>;
  testPipeline: (
    name: string,
    request?: PipelineTestRequest,
  ) => Promise<PipelineTestResult>;
  listTurns: () => Promise<TurnList>;
  getTurn: (turnId: string) => Promise<TurnSnapshot>;
  getTurnEvents: (turnId: string) => Promise<RawTurnEvents>;
}

export const conduitApiRoutes = {
  status: "/v1/status",
  events: "/v1/events",
  turns: "/v1/turns",
  liveTurns: "/v1/turns/live",
  turn: "/v1/turns/{turn_id}",
  turnEvents: "/v1/turns/{turn_id}/events",
  providerCatalog: "/v1/catalog/providers",
  providers: "/v1/providers",
  provider: "/v1/providers/{id}",
  providerTest: "/v1/providers/{id}/test",
  providerVoices: "/v1/providers/{id}/voices",
  providerPhrases: "/v1/providers/{id}/phrases",
  pipelines: "/v1/pipelines",
  pipeline: "/v1/pipelines/{name}",
  pipelineTest: "/v1/pipelines/{name}/test-turn",
  validatePipeline: "/v1/pipelines/validate",
} as const;

export function createConduitApiClient(
  config: ConduitApiClientConfig,
): ConduitApiClient {
  const request = config.fetch ?? fetch;

  return {
    routes: conduitApiRoutes,
    status: () =>
      requestJson<OperatorStatusSnapshot>(request, config, conduitApiRoutes.status),
    listPipelines: () =>
      requestJson<string[]>(request, config, conduitApiRoutes.pipelines),
    listProviderComponents: () =>
      requestJson<ProviderComponentCatalog>(
        request,
        config,
        conduitApiRoutes.providerCatalog,
      ),
    listProviderDefinitions: () =>
      requestJson<string[]>(request, config, conduitApiRoutes.providers),
    getProviderDefinition: (id) =>
      requestJson<ProviderDefinitionView>(request, config, providerRoute(id)),
    putProviderDefinition: (id, definition) =>
      requestJson<ProviderDefinitionView>(request, config, providerRoute(id), {
        method: "PUT",
        body: JSON.stringify(definition),
      }),
    deleteProviderDefinition: async (id) => {
      await requestJson<void>(request, config, providerRoute(id), {
        method: "DELETE",
      });
    },
    testProviderDefinition: (id) =>
      requestJson<ProviderStatus>(request, config, providerTestRoute(id), {
        method: "POST",
      }),
    listProviderVoices: (id) =>
      requestJson<ProviderVoices>(request, config, providerVoicesRoute(id)),
    listProviderPhrases: (id) =>
      requestJson<ProviderPhrases>(request, config, providerPhrasesRoute(id)),
    getPipeline: (name) =>
      requestJson<PipelineView>(request, config, pipelineRoute(name)),
    putPipeline: (name, graph) =>
      requestJson<PipelineView>(request, config, pipelineRoute(name), {
        method: "PUT",
        body: JSON.stringify(graph),
      }),
    deletePipeline: async (name) => {
      await requestJson<void>(request, config, pipelineRoute(name), {
        method: "DELETE",
      });
    },
    validatePipeline: (graph) =>
      requestJson<PipelineView>(request, config, conduitApiRoutes.validatePipeline, {
        method: "POST",
        body: JSON.stringify(graph),
      }),
    testPipeline: (name, testRequest = {}) =>
      requestJson<PipelineTestResult>(request, config, pipelineTestRoute(name), {
        method: "POST",
        body: JSON.stringify(testRequest),
      }),
    listTurns: () => requestJson<TurnList>(request, config, conduitApiRoutes.turns),
    getTurn: (turnId) =>
      requestJson<TurnSnapshot>(request, config, turnRoute(turnId)),
    getTurnEvents: (turnId) =>
      requestJson<RawTurnEvents>(request, config, turnEventsRoute(turnId)),
  };
}

function pipelineRoute(name: string): string {
  return conduitApiRoutes.pipeline.replace("{name}", encodeURIComponent(name));
}

function providerRoute(id: string): string {
  return conduitApiRoutes.provider.replace("{id}", encodeURIComponent(id));
}

function providerVoicesRoute(id: string): string {
  return conduitApiRoutes.providerVoices.replace(
    "{id}",
    encodeURIComponent(id),
  );
}

function providerPhrasesRoute(id: string): string {
  return conduitApiRoutes.providerPhrases.replace(
    "{id}",
    encodeURIComponent(id),
  );
}

function providerTestRoute(id: string): string {
  return conduitApiRoutes.providerTest.replace(
    "{id}",
    encodeURIComponent(id),
  );
}

function pipelineTestRoute(name: string): string {
  return conduitApiRoutes.pipelineTest.replace(
    "{name}",
    encodeURIComponent(name),
  );
}

function turnRoute(turnId: string): string {
  return conduitApiRoutes.turn.replace("{turn_id}", encodeURIComponent(turnId));
}

function turnEventsRoute(turnId: string): string {
  return conduitApiRoutes.turnEvents.replace("{turn_id}", encodeURIComponent(turnId));
}

async function requestJson<T>(
  request: typeof fetch,
  config: ConduitApiClientConfig,
  route: string,
  init: RequestInit = {},
): Promise<T> {
  const response = await request(new URL(route, config.baseUrl), {
    ...init,
    headers: {
      accept: "application/json",
      ...(init.body ? { "content-type": "application/json" } : {}),
      ...config.headers?.(),
      ...init.headers,
    },
  });

  if (!response.ok) {
    throw new Error(await failureMessage(response));
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}

/**
 * The API answers every failure with `{"error": ..., "detail": ...}`, and the
 * detail is the only part that says why — "no providers are configured" rather
 * than "422". Anything else is a body we cannot read, so the status line is all
 * that is left to report.
 */
async function failureMessage(response: Response): Promise<string> {
  const fallback =
    `Conduit API request failed: ${response.status} ${response.statusText}`.trimEnd();

  try {
    const body = (await response.json()) as { detail?: unknown };
    return typeof body.detail === "string" && body.detail.length > 0
      ? body.detail
      : fallback;
  } catch {
    return fallback;
  }
}

export const pipelineViewFixture = {
  "graph": {
    "name": "kitchen",
    "nodes": [
      {
        "kind": "source",
        "id": "mic",
        "provider": "websocket",
        "modality": "audio"
      },
      {
        "kind": "stt",
        "id": "stt",
        "provider": "whisper"
      },
      {
        "kind": "core",
        "id": "llm",
        "core": {
          "model": {
            "provider": "openai",
            "model": "gpt-4o-mini"
          },
          "max_rounds": 4
        }
      },
      {
        "kind": "tts",
        "id": "tts",
        "provider": "piper-local"
      },
      {
        "kind": "sink",
        "id": "speaker",
        "provider": "websocket",
        "modality": "audio"
      }
    ],
    "edges": [
      {
        "from": "mic",
        "to": "stt"
      },
      {
        "from": "stt",
        "to": "llm"
      },
      {
        "from": "llm",
        "to": "tts"
      },
      {
        "from": "tts",
        "to": "speaker"
      }
    ]
  },
  "order": [
    "mic",
    "stt",
    "llm",
    "tts",
    "speaker"
  ]
} as const satisfies PipelineView;
export const turnSnapshotFixture = {
  "conversation_id": "00000000-0000-0000-0000-000000000002",
  "ended_at": "2026-08-01T01:02:02Z",
  "items": [
    {
      "evidence": [
        "00000000-0000-0000-0000-00000000012d"
      ],
      "id": "assistant-preamble-1",
      "kind": "utterance_segment",
      "modality": "audio",
      "role": "assistant_preamble",
      "sequence": 2,
      "started_at": "2026-08-01T01:02:00Z",
      "text": "I will check the lights."
    },
    {
      "calls": [
        {
          "duration_ms": 34,
          "evidence": [
            "00000000-0000-0000-0000-00000000012e",
            "00000000-0000-0000-0000-00000000012f",
            "00000000-0000-0000-0000-000000000130"
          ],
          "id": "call_contract",
          "name": "lights.turn_on",
          "status": "completed"
        }
      ],
      "completed_at": "2026-08-01T01:02:01Z",
      "evidence": [
        "00000000-0000-0000-0000-00000000012c"
      ],
      "id": "round-1",
      "kind": "tool_batch",
      "model_round": 1,
      "sequence": 3,
      "started_at": "2026-08-01T01:02:00Z"
    },
    {
      "evidence": [
        "00000000-0000-0000-0000-000000000131"
      ],
      "id": "assistant-response-1",
      "kind": "utterance_segment",
      "modality": "audio",
      "role": "assistant_response",
      "sequence": 4,
      "started_at": "2026-08-01T01:02:01Z",
      "text": "The lights are on."
    }
  ],
  "pipeline_name": "kitchen",
  "sequence": 5,
  "started_at": "2026-08-01T01:01:59Z",
  "status": "completed",
  "turn_id": "00000000-0000-0000-0000-000000000003"
} as const satisfies TurnSnapshot;
