// Generated by crates/conduit-api/tests/frontend_contract.rs. Do not edit by hand.

import type { OperatorStatusSnapshot } from "./status";

export type IdString = string;
export type NodeKind =
  | "source"
  | "wake_word"
  | "stt"
  | "speaker_id"
  | "router"
  | "llm"
  | "tool"
  | "memory"
  | "tts"
  | "sink";

export interface PipelineNode {
  id: IdString;
  kind: NodeKind;
  provider: string;
  config?: unknown;
}

export interface PipelineEdge {
  from: IdString;
  to: IdString;
  port?: string;
}

export interface PipelineGraph {
  name: string;
  nodes: PipelineNode[];
  edges: PipelineEdge[];
}

export interface PipelineView {
  graph: PipelineGraph;
  order: IdString[];
}

export interface ConduitApiClientConfig {
  baseUrl: string;
  headers?: () => HeadersInit;
  fetch?: typeof fetch;
}

export interface ConduitApiClient {
  readonly routes: typeof conduitApiRoutes;
  status: () => Promise<OperatorStatusSnapshot>;
  listPipelines: () => Promise<string[]>;
  getPipeline: (name: string) => Promise<PipelineView>;
  putPipeline: (name: string, graph: PipelineGraph) => Promise<PipelineView>;
  deletePipeline: (name: string) => Promise<void>;
  validatePipeline: (graph: PipelineGraph) => Promise<PipelineView>;
}

export const conduitApiRoutes = {
  status: "/v1/status",
  events: "/v1/events",
  pipelines: "/v1/pipelines",
  pipeline: "/v1/pipelines/{name}",
  validatePipeline: "/v1/pipelines/validate",
} as const;

export function createConduitApiClient(
  config: ConduitApiClientConfig,
): ConduitApiClient {
  const request = config.fetch ?? fetch;

  return {
    routes: conduitApiRoutes,
    status: () =>
      requestJson<OperatorStatusSnapshot>(request, config, conduitApiRoutes.status),
    listPipelines: () =>
      requestJson<string[]>(request, config, conduitApiRoutes.pipelines),
    getPipeline: (name) =>
      requestJson<PipelineView>(request, config, pipelineRoute(name)),
    putPipeline: (name, graph) =>
      requestJson<PipelineView>(request, config, pipelineRoute(name), {
        method: "PUT",
        body: JSON.stringify(graph),
      }),
    deletePipeline: async (name) => {
      await requestJson<void>(request, config, pipelineRoute(name), {
        method: "DELETE",
      });
    },
    validatePipeline: (graph) =>
      requestJson<PipelineView>(request, config, conduitApiRoutes.validatePipeline, {
        method: "POST",
        body: JSON.stringify(graph),
      }),
  };
}

function pipelineRoute(name: string): string {
  return conduitApiRoutes.pipeline.replace("{name}", encodeURIComponent(name));
}

async function requestJson<T>(
  request: typeof fetch,
  config: ConduitApiClientConfig,
  route: string,
  init: RequestInit = {},
): Promise<T> {
  const response = await request(new URL(route, config.baseUrl), {
    ...init,
    headers: {
      accept: "application/json",
      ...(init.body ? { "content-type": "application/json" } : {}),
      ...config.headers?.(),
      ...init.headers,
    },
  });

  if (!response.ok) {
    throw new Error(`Conduit API request failed: ${response.status} ${response.statusText}`);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}

export const pipelineViewFixture = {
  "graph": {
    "name": "kitchen",
    "nodes": [
      {
        "id": "mic",
        "kind": "source",
        "provider": "websocket"
      },
      {
        "id": "stt",
        "kind": "stt",
        "provider": "whisper"
      },
      {
        "id": "llm",
        "kind": "llm",
        "provider": "openai"
      },
      {
        "id": "tts",
        "kind": "tts",
        "provider": "piper-local"
      },
      {
        "id": "speaker",
        "kind": "sink",
        "provider": "websocket"
      }
    ],
    "edges": [
      {
        "from": "mic",
        "to": "stt"
      },
      {
        "from": "stt",
        "to": "llm"
      },
      {
        "from": "llm",
        "to": "tts"
      },
      {
        "from": "tts",
        "to": "speaker"
      }
    ]
  },
  "order": [
    "mic",
    "stt",
    "llm",
    "tts",
    "speaker"
  ]
} as const satisfies PipelineView;
