// Generated by crates/conduit-api/tests/frontend_contract.rs. Do not edit by hand.

import type { EventType } from "./events";

export type DateTimeString = string;
export type IdString = string;

export type LaunchState = "first_run_setup" | "operations_workspace";
export type StaleState = "fresh" | "stale";
export type PipelineHealthState = "not_runnable" | "unproven" | "healthy" | "degraded" | "unhealthy";
export type ComponentKind = "capture" | "transcription" | "reasoning" | "tools" | "synthesis";
export type ComponentHealthState = "not_configured" | "unused" | "unproven" | "healthy" | "degraded" | "unhealthy";
export type ProviderKind = "stt" | "llm" | "tool" | "tts";
export type ProviderStatusState = "unavailable" | "configured" | "reachable" | "proven";
export type SnapshotResource =
  | "runtime_state"
  | "pipeline_health"
  | "provider_status"
  | "satellite_status"
  | "active_turns"
  | "recent_failures";

export interface OperatorStatusSnapshot {
  generated_at: DateTimeString;
  runtime: RuntimeState;
  pipelines: PipelineStatus[];
  providers: ProviderStatus[];
  satellites: SatelliteStatus;
  active_turns: ActiveTurnStatus[];
  recent_failures: RuntimeFailure[];
  event_stream: EventStreamContract;
}

export interface RuntimeState {
  launch_state: LaunchState;
  stale_state: StaleState;
}

export interface PipelineStatus {
  name: string;
  usable: boolean;
  health: PipelineHealth;
  components: ComponentHealth[];
  affected_providers: string[];
}

export interface PipelineHealth {
  state: PipelineHealthState;
  summary: string;
  last_successful_turn: IdString | null;
  last_failed_turn: IdString | null;
}

export interface ComponentHealth {
  kind: ComponentKind;
  provider: string | null;
  state: ComponentHealthState;
  detail: string | null;
  last_turn: IdString | null;
}

export interface ProviderStatus {
  id: string;
  kind: ProviderKind;
  state: ProviderStatusState;
  configured: boolean;
  reachable: boolean;
  proven_by_turn: IdString | null;
  message: string | null;
  affects_pipelines: string[];
}

export interface SatelliteStatus {
  connected: ConnectedSatellite[];
  recently_active: RecentlyActiveSatellite[];
  recent_window_seconds: number;
}

export interface ConnectedSatellite {
  device: IdString;
  name: string;
  connected_since: DateTimeString;
  conversation: IdString | null;
  pipeline: string;
}

export interface RecentlyActiveSatellite {
  device: IdString;
  name: string;
  last_seen_at: DateTimeString;
  last_event: string;
}

export interface ActiveTurnStatus {
  pipeline: string;
  conversation: IdString;
  turn: IdString;
  trace: IdString;
  started_at: DateTimeString;
  invoked_components: ComponentKind[];
}

export interface RuntimeFailure {
  pipeline: string;
  turn: IdString | null;
  component: ComponentKind;
  provider: string | null;
  message: string;
  at: DateTimeString;
}

export interface EventStreamContract {
  route: string;
  stale_state_on_disconnect: StaleState;
  refresh_snapshot_after_reconnect: boolean;
  bindings: SnapshotEventBinding[];
}

export interface SnapshotEventBinding {
  resource: SnapshotResource;
  events: EventType[];
}

export const operatorStatusSnapshotFixture = {
  "generated_at": "2026-08-01T01:02:03Z",
  "runtime": {
    "launch_state": "operations_workspace",
    "stale_state": "fresh"
  },
  "pipelines": [
    {
      "name": "kitchen",
      "usable": true,
      "health": {
        "state": "unhealthy",
        "summary": "speech synthesis failed after the model completed",
        "last_successful_turn": null,
        "last_failed_turn": "00000000-0000-0000-0000-000000000003"
      },
      "components": [
        {
          "kind": "reasoning",
          "provider": "openai-primary",
          "state": "healthy",
          "detail": "last invoked turn completed",
          "last_turn": "00000000-0000-0000-0000-000000000003"
        },
        {
          "kind": "synthesis",
          "provider": "piper-local",
          "state": "unhealthy",
          "detail": "connection refused",
          "last_turn": "00000000-0000-0000-0000-000000000003"
        }
      ],
      "affected_providers": [
        "piper-local"
      ]
    }
  ],
  "providers": [
    {
      "id": "piper-local",
      "kind": "tts",
      "state": "configured",
      "configured": true,
      "reachable": false,
      "proven_by_turn": null,
      "message": "no successful reachability check yet",
      "affects_pipelines": [
        "kitchen"
      ]
    }
  ],
  "satellites": {
    "connected": [
      {
        "device": "00000000-0000-0000-0000-000000000001",
        "name": "Kitchen Satellite",
        "connected_since": "2026-08-01T01:01:50Z",
        "conversation": "00000000-0000-0000-0000-000000000002",
        "pipeline": "kitchen"
      }
    ],
    "recently_active": [
      {
        "device": "00000000-0000-0000-0000-000000000001",
        "name": "Kitchen Satellite",
        "last_seen_at": "2026-08-01T01:01:58Z",
        "last_event": "TtsStarted"
      }
    ],
    "recent_window_seconds": 300
  },
  "active_turns": [
    {
      "pipeline": "kitchen",
      "conversation": "00000000-0000-0000-0000-000000000002",
      "turn": "00000000-0000-0000-0000-000000000003",
      "trace": "00000000-0000-0000-0000-000000000004",
      "started_at": "2026-08-01T01:01:59Z",
      "invoked_components": [
        "reasoning",
        "synthesis"
      ]
    }
  ],
  "recent_failures": [
    {
      "pipeline": "kitchen",
      "turn": "00000000-0000-0000-0000-000000000003",
      "component": "synthesis",
      "provider": "piper-local",
      "message": "connection refused",
      "at": "2026-08-01T01:02:01Z"
    }
  ],
  "event_stream": {
    "route": "/v1/events",
    "stale_state_on_disconnect": "stale",
    "refresh_snapshot_after_reconnect": true,
    "bindings": [
      {
        "resource": "pipeline_health",
        "events": [
          "TurnStarted",
          "StageFailed",
          "ConversationCompleted",
          "ConversationCancelled"
        ]
      },
      {
        "resource": "active_turns",
        "events": [
          "TurnStarted",
          "ConversationCompleted",
          "ConversationCancelled"
        ]
      },
      {
        "resource": "recent_failures",
        "events": [
          "StageFailed",
          "ConversationCompleted"
        ]
      },
      {
        "resource": "satellite_status",
        "events": [
          "ConversationStarted",
          "AudioStarted",
          "ConversationCompleted",
          "ConversationCancelled"
        ]
      }
    ]
  }
} as const satisfies OperatorStatusSnapshot;
